# Generated by Django 5.1.1 on 2025-04-27 05:07

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
