# Generated by Django 5.1.1 on 2025-05-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blogpost_slug_blogpostimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPostImage',
        ),
    ]
