# Generated by Django 5.1.1 on 2025-05-03 19:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_blogpostimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='1200x500 image recommended', null=True, upload_to=api.models.blog_cover_image_upload_path),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='150x150 image recommended', null=True, upload_to=api.models.blog_preview_image_upload_path),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='spotlight',
            field=models.BooleanField(default=False),
        ),
    ]
