# Generated by Django 5.1.1 on 2025-05-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blogpost_cover_image_blogpost_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
