# Generated by Django 5.1.1 on 2025-05-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Bayardo Lopez', max_length=100),
        ),
    ]
